### ISSUE TITLE
999 used for missing values?

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/azmetr#22]
Looks like at least `dwpt` uses 999 for a missing value.  This wasn't reflected in the metadata shared by @jeremylweiss. 

``` r
library(azmetr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
az_hourly(station_id = 22, start_date_time = "2021-03-29 14", end_date_time = "2021-03-29 16") |> 
  select(meta_station_id, date_datetime, dwpt, dwptF)
#> # A tibble: 3 × 4
#>   meta_station_id date_datetime        dwpt dwptF
#>   <chr>           <dttm>              <dbl> <dbl>
#> 1 az22            2021-03-29 14:00:00 999   999  
#> 2 az22            2021-03-29 15:00:00 999   999  
#> 3 az22            2021-03-29 16:00:00  -5.4  22.4
```

<sup>Created on 2022-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jeremylweiss** [comment]
I just checked some AZMet data milestones, and this makes sense. Information for noData values from the 'azmet-data-metadata' file only applies to data after 9/22/2022 (the date when Matt Harmon 'hardwired' it into the API system). For prior data, noData values are back to either -7999 or the legacy lineup (999, 999.9, or 9999).
